### ISSUE TITLE
Porting template matching to python

### ISSUE THREAD

**Issue by phisanti** [qztseng/imagej_plugins#6]
Hi,

I was thinking about porting the code of the template matching to Python. Do you think that could be an issue? I will reference you in the documentation.

**Comment by qztseng** [comment]
No problem, please go ahead. :-)

**Comment by phisanti** [comment]
Hi, 

I wanted to reach out and express my gratitude. I was using for a time `pystackreg`, but noticed that their alignment at frame 0-1 was not as good as the use of template matching. Thus, I end up writing the port to Python. You can see it in [this repo](https://github.com/phisanti/TemplateMatchingPy). I have added references to your work, so I hope that I managed to honour your work. Thank you very much for developing such a great code. I have used your Fiji plug-in a lot for many years, and it made me very happy that I can contribute to bringing it to Python.

**Comment by qztseng** [comment]
Thanks a lot! Glad you found it useful — I hope it helps others too! 😊
